from .de_phone_number_recognizer import PhoneNumberRecognizer
from .email_recognizer import EmailRecognizer
from .flair_statistical_recognizer import FlairStatisticalRecognizer
from .spacy_statistical_recognizer import SpacyStatisticalRecognizer

__all__ = (EmailRecognizer, FlairStatisticalRecognizer, PhoneNumberRecognizer, SpacyStatisticalRecognizer)
