from .de_phone_number_recognizer import DePhoneNumberRecognizer
from .de_state_recognizer import DeStateRecognizer
from .email_recognizer import EmailRecognizer
from .flair_statistical_recognizer import FlairStatisticalRecognizer
from .spacy_statistical_recognizer import SpacyStatisticalRecognizer

__all__ = (DePhoneNumberRecognizer, DeStateRecognizer, EmailRecognizer, FlairStatisticalRecognizer, SpacyStatisticalRecognizer)
